### ISSUE TITLE
Not starting scince version 0.1.2

### ISSUE THREAD

**Issue by scolastico** [scolastico-dev/s.Status#33]
### **Describe the bug**
The application crashes because it cant find a driver

### **To Reproduce**
1. Download newest release
2. Start the application with mysql as database

### **Expected behavior**
Normal starting

### **Additional context**
```
Message: Error initialising DataSource with user: statuspage url:jdbc:mariadb://localhost:3306/statuspage?useLegacyDatetimeCode=false error:No suitable driver found for jdbc:mariadb://localhost:3306/statuspage?useLegacyDatetimeCode=false
StackTrace:
io.ebean.datasource.DataSourceInitialiseException: Error initialising DataSource with user: statuspage url:jdbc:mariadb://localhost:3306/statuspage?useLegacyDatetimeCode=false error:No suitable driver found for jdbc:mariadb://localhost:3306/statuspage?useLegacyDatetimeCode=false
        at io.ebean.datasource.pool.ConnectionPool.init(ConnectionPool.java:165)
        at io.ebean.datasource.pool.ConnectionPool.<init>(ConnectionPool.java:154)
        at io.ebean.datasource.pool.ConnectionPoolFactory.createPool(ConnectionPoolFactory.java:14)
        at io.ebean.datasource.DataSourceFactory.create(DataSourceFactory.java:26)
        at io.ebeaninternal.server.core.InitDataSource.create(InitDataSource.java:120)
        at io.ebeaninternal.server.core.InitDataSource.createFromConfig(InitDataSource.java:115)
        at io.ebeaninternal.server.core.InitDataSource.initDataSource(InitDataSource.java:48)
        at io.ebeaninternal.server.core.InitDataSource.initialise(InitDataSource.java:33)
        at io.ebeaninternal.server.core.InitDataSource.init(InitDataSource.java:24)
        at io.ebeaninternal.server.core.DefaultContainer.setDataSource(DefaultContainer.java:220)
        at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:91)
        at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:35)
        at io.ebean.DatabaseFactory.createInternal(DatabaseFactory.java:136)
        at io.ebean.DatabaseFactory.create(DatabaseFactory.java:85)
        at me.scolastico.s.status.Application.main(Application.java:174)
Caused by: java.sql.SQLException: No suitable driver found for jdbc:mariadb://localhost:3306/statuspage?useLegacyDatetimeCode=false
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:702)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:189)
        at io.ebean.datasource.pool.ConnectionPool.createUnpooledConnection(ConnectionPool.java:447)
        at io.ebean.datasource.pool.ConnectionPool.createUnpooledConnection(ConnectionPool.java:442)
        at io.ebean.datasource.pool.ConnectionPool.createConnectionForQueue(ConnectionPool.java:661)
        at io.ebean.datasource.pool.PooledConnectionQueue.ensureMinimumConnections(PooledConnectionQueue.java:158)
        at io.ebean.datasource.pool.ConnectionPool.initialiseConnections(ConnectionPool.java:195)
        at io.ebean.datasource.pool.ConnectionPool.init(ConnectionPool.java:163)
        ... 14 more
```

**Comment by scolastico** [comment]
fixed
